//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebA1.Models.New_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Product_ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Created_by { get; set; }
        public string Category_Id { get; set; }
        public string Cost { get; set; }
    }
}
